-- Migration: 20260223103000_FixCircleSubjectIdTypes
-- Description: Fix Circle table SubjectId columns from int to uuid
-- Issue: AlterColumn() in EF Core silently fails on PostgreSQL for int→uuid
-- Tables: Circle, CircleMember, CircleRecipe, CircleInvite

BEGIN;

DO $$
BEGIN
    -- Check if migration already applied
    IF EXISTS (
        SELECT 1 FROM public."__EFMigrationsHistory" 
        WHERE "MigrationId" = '20260223103000_FixCircleSubjectIdTypes'
    ) THEN
        RAISE NOTICE '⏭️  Migration 20260223103000_FixCircleSubjectIdTypes already applied - skipping';
        RETURN;
    END IF;

    RAISE NOTICE '🔧 Applying migration: 20260223103000_FixCircleSubjectIdTypes';

    -- Check if Circle table exists and needs fix
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'Circle'
          AND column_name = 'OwnerSubjectId'
          AND data_type IN ('integer', 'bigint')
    ) THEN
        RAISE NOTICE '   Circle.OwnerSubjectId is already uuid or table does not exist - skipping table recreation';
    ELSE
        -- Verify tables are empty before DROP
        IF (SELECT COUNT(*) FROM public."Circle") > 0 THEN
            RAISE EXCEPTION '❌ Circle table contains data - manual migration required';
        END IF;
        IF (SELECT COUNT(*) FROM public."CircleMember") > 0 THEN
            RAISE EXCEPTION '❌ CircleMember table contains data - manual migration required';
        END IF;
        IF (SELECT COUNT(*) FROM public."CircleRecipe") > 0 THEN
            RAISE EXCEPTION '❌ CircleRecipe table contains data - manual migration required';
        END IF;
        IF (SELECT COUNT(*) FROM public."CircleInvite") > 0 THEN
            RAISE EXCEPTION '❌ CircleInvite table contains data - manual migration required';
        END IF;

        RAISE NOTICE '   Dropping Circle tables...';
        
        DROP TABLE IF EXISTS public."CircleRecipe" CASCADE;
        DROP TABLE IF EXISTS public."CircleInvite" CASCADE;
        DROP TABLE IF EXISTS public."CircleMember" CASCADE;
        DROP TABLE IF EXISTS public."Circle" CASCADE;

        RAISE NOTICE '   Creating Circle with uuid columns...';
        
        CREATE TABLE public."Circle" (
            "CircleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CircleResourceId" uuid NOT NULL,
            "Name" character varying(100) NOT NULL,
            "Description" character varying(500),
            "OwnerSubjectId" uuid NOT NULL,
            "CreatedDate" timestamp with time zone NOT NULL,
            "CreatedSubjectId" uuid NOT NULL,
            "LastModifiedDate" timestamp with time zone NOT NULL,
            "LastModifiedSubjectId" uuid NOT NULL
        );

        CREATE UNIQUE INDEX "IX_Circle_CircleResourceId" ON public."Circle" ("CircleResourceId");
        CREATE INDEX "IX_Circle_CreatedSubjectId" ON public."Circle" ("CreatedSubjectId");
        CREATE INDEX "IX_Circle_LastModifiedSubjectId" ON public."Circle" ("LastModifiedSubjectId");

        ALTER TABLE public."Circle" ADD CONSTRAINT "FK_Circle_Subject_CreatedSubjectId"
            FOREIGN KEY ("CreatedSubjectId") REFERENCES public."Subject" ("SubjectId");
        ALTER TABLE public."Circle" ADD CONSTRAINT "FK_Circle_Subject_LastModifiedSubjectId"
            FOREIGN KEY ("LastModifiedSubjectId") REFERENCES public."Subject" ("SubjectId");

        RAISE NOTICE '   Creating CircleMember with uuid columns...';
        
        CREATE TABLE public."CircleMember" (
            "CircleMemberId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CircleId" integer NOT NULL,
            "SubjectId" uuid NOT NULL,
            "Role" integer NOT NULL,
            "Status" integer NOT NULL,
            "JoinedDate" timestamp with time zone,
            "InvitedDate" timestamp with time zone
        );

        CREATE UNIQUE INDEX "IX_CircleMember_CircleId_SubjectId" ON public."CircleMember" ("CircleId", "SubjectId");
        CREATE INDEX "IX_CircleMember_SubjectId" ON public."CircleMember" ("SubjectId");

        ALTER TABLE public."CircleMember" ADD CONSTRAINT "FK_CircleMember_Circle_CircleId"
            FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;
        ALTER TABLE public."CircleMember" ADD CONSTRAINT "FK_CircleMember_Subject_SubjectId"
            FOREIGN KEY ("SubjectId") REFERENCES public."Subject" ("SubjectId");

        RAISE NOTICE '   Creating CircleRecipe with uuid columns...';
        
        CREATE TABLE public."CircleRecipe" (
            "CircleRecipeId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CircleId" integer NOT NULL,
            "RecipeId" integer NOT NULL,
            "SharedBySubjectId" uuid NOT NULL,
            "SharedDate" timestamp with time zone NOT NULL
        );

        CREATE UNIQUE INDEX "IX_CircleRecipe_CircleId_RecipeId" ON public."CircleRecipe" ("CircleId", "RecipeId");
        CREATE INDEX "IX_CircleRecipe_RecipeId" ON public."CircleRecipe" ("RecipeId");

        ALTER TABLE public."CircleRecipe" ADD CONSTRAINT "FK_CircleRecipe_Circle_CircleId"
            FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;
        ALTER TABLE public."CircleRecipe" ADD CONSTRAINT "FK_CircleRecipe_Recipe_RecipeId"
            FOREIGN KEY ("RecipeId") REFERENCES public."Recipe" ("RecipeId") ON DELETE RESTRICT;

        RAISE NOTICE '   Creating CircleInvite with uuid columns...';
        
        CREATE TABLE public."CircleInvite" (
            "CircleInviteId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "InviteToken" uuid NOT NULL,
            "CircleId" integer NOT NULL,
            "InviteeEmail" character varying(255),
            "InvitedBySubjectId" uuid NOT NULL,
            "CreatedDate" timestamp with time zone NOT NULL,
            "ExpiresDate" timestamp with time zone NOT NULL,
            "Status" integer NOT NULL
        );

        CREATE UNIQUE INDEX "IX_CircleInvite_InviteToken" ON public."CircleInvite" ("InviteToken");
        CREATE INDEX "IX_CircleInvite_CircleId" ON public."CircleInvite" ("CircleId");

        ALTER TABLE public."CircleInvite" ADD CONSTRAINT "FK_CircleInvite_Circle_CircleId"
            FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;

        RAISE NOTICE '   ✓ Circle tables recreated with uuid columns';
    END IF;

    -- Record migration
    INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260223103000_FixCircleSubjectIdTypes', '8.0.0');

    RAISE NOTICE '✅ Migration 20260223103000_FixCircleSubjectIdTypes applied';
END $$;

COMMIT;
