-- HOTFIX: Fix CircleMember/CircleRecipe/CircleInvite/Circle SubjectId types from int to uuid
-- Safe to run: Tables should be empty (feature just launched)
-- Run this in Supabase SQL Editor

-- First, verify tables are empty (abort if not)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public."Circle" LIMIT 1) THEN
        RAISE EXCEPTION 'Circle table is not empty! Cannot apply hotfix.';
    END IF;
    IF EXISTS (SELECT 1 FROM public."CircleMember" LIMIT 1) THEN
        RAISE EXCEPTION 'CircleMember table is not empty! Cannot apply hotfix.';
    END IF;
    IF EXISTS (SELECT 1 FROM public."CircleRecipe" LIMIT 1) THEN
        RAISE EXCEPTION 'CircleRecipe table is not empty! Cannot apply hotfix.';
    END IF;
    IF EXISTS (SELECT 1 FROM public."CircleInvite" LIMIT 1) THEN
        RAISE EXCEPTION 'CircleInvite table is not empty! Cannot apply hotfix.';
    END IF;
END $$;

-- Drop tables in dependency order (children first)
DROP TABLE IF EXISTS public."CircleRecipe" CASCADE;
DROP TABLE IF EXISTS public."CircleInvite" CASCADE;
DROP TABLE IF EXISTS public."CircleMember" CASCADE;
DROP TABLE IF EXISTS public."Circle" CASCADE;

-- Recreate Circle with correct types
CREATE TABLE public."Circle" (
    "CircleId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CircleResourceId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "OwnerSubjectId" uuid NOT NULL,  -- FIXED: was int
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedSubjectId" uuid NOT NULL,
    "LastModifiedDate" timestamp with time zone NOT NULL,
    "LastModifiedSubjectId" uuid NOT NULL
);

CREATE UNIQUE INDEX "IX_Circle_CircleResourceId" ON public."Circle" ("CircleResourceId");
CREATE INDEX "IX_Circle_CreatedSubjectId" ON public."Circle" ("CreatedSubjectId");
CREATE INDEX "IX_Circle_LastModifiedSubjectId" ON public."Circle" ("LastModifiedSubjectId");

ALTER TABLE public."Circle" ADD CONSTRAINT "FK_Circle_Subject_CreatedSubjectId"
    FOREIGN KEY ("CreatedSubjectId") REFERENCES public."Subject" ("SubjectId");
ALTER TABLE public."Circle" ADD CONSTRAINT "FK_Circle_Subject_LastModifiedSubjectId"
    FOREIGN KEY ("LastModifiedSubjectId") REFERENCES public."Subject" ("SubjectId");

-- Recreate CircleMember with correct types
CREATE TABLE public."CircleMember" (
    "CircleMemberId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CircleId" integer NOT NULL,
    "SubjectId" uuid NOT NULL,  -- FIXED: was int
    "Role" integer NOT NULL,
    "Status" integer NOT NULL,
    "JoinedDate" timestamp with time zone,
    "InvitedDate" timestamp with time zone
);

CREATE UNIQUE INDEX "IX_CircleMember_CircleId_SubjectId" ON public."CircleMember" ("CircleId", "SubjectId");
CREATE INDEX "IX_CircleMember_SubjectId" ON public."CircleMember" ("SubjectId");

ALTER TABLE public."CircleMember" ADD CONSTRAINT "FK_CircleMember_Circle_CircleId"
    FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;
ALTER TABLE public."CircleMember" ADD CONSTRAINT "FK_CircleMember_Subject_SubjectId"
    FOREIGN KEY ("SubjectId") REFERENCES public."Subject" ("SubjectId");

-- Recreate CircleRecipe with correct types
CREATE TABLE public."CircleRecipe" (
    "CircleRecipeId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CircleId" integer NOT NULL,
    "RecipeId" integer NOT NULL,
    "SharedBySubjectId" uuid NOT NULL,  -- FIXED: was int
    "SharedDate" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX "IX_CircleRecipe_CircleId_RecipeId" ON public."CircleRecipe" ("CircleId", "RecipeId");
CREATE INDEX "IX_CircleRecipe_RecipeId" ON public."CircleRecipe" ("RecipeId");

ALTER TABLE public."CircleRecipe" ADD CONSTRAINT "FK_CircleRecipe_Circle_CircleId"
    FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;
ALTER TABLE public."CircleRecipe" ADD CONSTRAINT "FK_CircleRecipe_Recipe_RecipeId"
    FOREIGN KEY ("RecipeId") REFERENCES public."Recipe" ("RecipeId") ON DELETE RESTRICT;

-- Recreate CircleInvite with correct types
CREATE TABLE public."CircleInvite" (
    "CircleInviteId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InviteToken" uuid NOT NULL,
    "CircleId" integer NOT NULL,
    "InviteeEmail" character varying(255),
    "InvitedBySubjectId" uuid NOT NULL,  -- FIXED: was int
    "CreatedDate" timestamp with time zone NOT NULL,
    "ExpiresDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL
);

CREATE UNIQUE INDEX "IX_CircleInvite_InviteToken" ON public."CircleInvite" ("InviteToken");
CREATE INDEX "IX_CircleInvite_CircleId" ON public."CircleInvite" ("CircleId");

ALTER TABLE public."CircleInvite" ADD CONSTRAINT "FK_CircleInvite_Circle_CircleId"
    FOREIGN KEY ("CircleId") REFERENCES public."Circle" ("CircleId") ON DELETE CASCADE;

-- Update migration history to mark both migrations as applied
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260223025127_FixCircleSubjectIdTypes', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

SELECT 'SUCCESS: Circle tables recreated with correct UUID types' as result;
