-- Manual migration script for pending migrations
-- Generated on 2026-03-08
-- Contains migrations from 2026-02-28 onward that weren't in pending.sql

START TRANSACTION;

-- Migration: 20260228120000_AddBetaInviteCodes
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228120000_AddBetaInviteCodes') THEN
        CREATE TABLE public."BetaInviteCode" (
            "BetaInviteCodeId" integer GENERATED BY DEFAULT AS IDENTITY,
            "BetaInviteCodeResourceId" uuid NOT NULL,
            "Code" character varying(20) NOT NULL,
            "MaxUses" integer NOT NULL,
            "UseCount" integer NOT NULL,
            "IsActive" boolean NOT NULL,
            "ExpiresDate" timestamp with time zone,
            "CreatedDate" timestamp with time zone NOT NULL,
            "CreatedSubjectId" uuid NOT NULL,
            "LastModifiedDate" timestamp with time zone NOT NULL,
            "LastModifiedSubjectId" uuid NOT NULL,
            CONSTRAINT "PK_BetaInviteCode" PRIMARY KEY ("BetaInviteCodeId"),
            CONSTRAINT "FK_BetaInviteCode_Subject_CreatedSubjectId" FOREIGN KEY ("CreatedSubjectId") REFERENCES public."Subject" ("SubjectId"),
            CONSTRAINT "FK_BetaInviteCode_Subject_LastModifiedSubjectId" FOREIGN KEY ("LastModifiedSubjectId") REFERENCES public."Subject" ("SubjectId")
        );

        CREATE TABLE public."BetaInviteCodeRedemption" (
            "BetaInviteCodeRedemptionId" integer GENERATED BY DEFAULT AS IDENTITY,
            "BetaInviteCodeId" integer NOT NULL,
            "SubjectId" uuid NOT NULL,
            "RedeemedDate" timestamp with time zone NOT NULL,
            CONSTRAINT "PK_BetaInviteCodeRedemption" PRIMARY KEY ("BetaInviteCodeRedemptionId"),
            CONSTRAINT "FK_BetaInviteCodeRedemption_BetaInviteCode_BetaInviteCodeId" FOREIGN KEY ("BetaInviteCodeId") REFERENCES public."BetaInviteCode" ("BetaInviteCodeId") ON DELETE CASCADE
        );

        CREATE UNIQUE INDEX "IX_BetaInviteCode_BetaInviteCodeResourceId" ON public."BetaInviteCode" ("BetaInviteCodeResourceId");
        CREATE UNIQUE INDEX "IX_BetaInviteCode_Code" ON public."BetaInviteCode" ("Code");
        CREATE INDEX "IX_BetaInviteCode_CreatedSubjectId" ON public."BetaInviteCode" ("CreatedSubjectId");
        CREATE INDEX "IX_BetaInviteCode_LastModifiedSubjectId" ON public."BetaInviteCode" ("LastModifiedSubjectId");
        CREATE INDEX "IX_BetaInviteCodeRedemption_BetaInviteCodeId" ON public."BetaInviteCodeRedemption" ("BetaInviteCodeId");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260228120000_AddBetaInviteCodes', '9.0.3');
    END IF;
END $EF$;

-- Migration: 20260228120000_AddUserAccount
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260228120000_AddUserAccount') THEN
        CREATE TABLE public."UserAccount" (
            "UserAccountId" integer GENERATED BY DEFAULT AS IDENTITY,
            "UserAccountResourceId" uuid NOT NULL,
            "SubjectId" uuid NOT NULL,
            "AccountTier" integer NOT NULL,
            "TierChangedDate" timestamp with time zone,
            "CreatedDate" timestamp with time zone NOT NULL,
            "CreatedSubjectId" uuid NOT NULL,
            "LastModifiedDate" timestamp with time zone NOT NULL,
            "LastModifiedSubjectId" uuid NOT NULL,
            CONSTRAINT "PK_UserAccount" PRIMARY KEY ("UserAccountId"),
            CONSTRAINT "FK_UserAccount_Subject_CreatedSubjectId" FOREIGN KEY ("CreatedSubjectId") REFERENCES public."Subject" ("SubjectId"),
            CONSTRAINT "FK_UserAccount_Subject_LastModifiedSubjectId" FOREIGN KEY ("LastModifiedSubjectId") REFERENCES public."Subject" ("SubjectId")
        );

        CREATE INDEX "IX_UserAccount_CreatedSubjectId" ON public."UserAccount" ("CreatedSubjectId");
        CREATE INDEX "IX_UserAccount_LastModifiedSubjectId" ON public."UserAccount" ("LastModifiedSubjectId");
        CREATE UNIQUE INDEX "IX_UserAccount_SubjectId" ON public."UserAccount" ("SubjectId");
        CREATE UNIQUE INDEX "IX_UserAccount_UserAccountResourceId" ON public."UserAccount" ("UserAccountResourceId");

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260228120000_AddUserAccount', '9.0.3');
    END IF;
END $EF$;

-- Migration: 20260308000001_AddRecipeForkCount
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260308000001_AddRecipeForkCount') THEN
        ALTER TABLE public."Recipe" ADD COLUMN "ForkCount" integer NOT NULL DEFAULT 0;

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20260308000001_AddRecipeForkCount', '9.0.3');
    END IF;
END $EF$;

COMMIT;

-- NOTE: SeedEquipment migration (20260303180000) intentionally skipped - data-only migration, check migrations-equipment-seed.sql instead
