// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeVault.Data;

#nullable disable

namespace RecipeVault.Data.Migrations
{
    [DbContext(typeof(RecipeVaultDbContext))]
    [Migration("20260227005451_ConsolidatedNewFeatures")]
    partial class ConsolidatedNewFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cortside.AspNetCore.Auditable.Entities.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasComment("Subject primary key");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Subject Surname ()");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Subject primary key");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Subject primary key");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Username (upn claim)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subject", "public", t =>
                        {
                            t.HasTrigger("trSubject");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.AvoidedIngredient", b =>
                {
                    b.Property<int>("AvoidedIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvoidedIngredientId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("DietaryProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AvoidedIngredientId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("DietaryProfileId", "IngredientName");

                    b.ToTable("AvoidedIngredient", "public", t =>
                        {
                            t.HasTrigger("trAvoidedIngredient");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Circle", b =>
                {
                    b.Property<int>("CircleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CircleId"));

                    b.Property<Guid>("CircleResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerSubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("CircleId");

                    b.HasIndex("CircleResourceId")
                        .IsUnique();

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("Circle", "public", t =>
                        {
                            t.HasTrigger("trCircle");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleInvite", b =>
                {
                    b.Property<int>("CircleInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CircleInviteId"));

                    b.Property<int>("CircleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InviteToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedBySubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteeEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CircleInviteId");

                    b.HasIndex("CircleId");

                    b.HasIndex("InviteToken")
                        .IsUnique();

                    b.ToTable("CircleInvite", "public", t =>
                        {
                            t.HasTrigger("trCircleInvite");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleMember", b =>
                {
                    b.Property<int>("CircleMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CircleMemberId"));

                    b.Property<int>("CircleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InvitedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("CircleMemberId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("CircleId", "SubjectId")
                        .IsUnique();

                    b.ToTable("CircleMember", "public", t =>
                        {
                            t.HasTrigger("trCircleMember");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleRecipe", b =>
                {
                    b.Property<int>("CircleRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CircleRecipeId"));

                    b.Property<int>("CircleId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SharedBySubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SharedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CircleRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("CircleId", "RecipeId")
                        .IsUnique();

                    b.ToTable("CircleRecipe", "public", t =>
                        {
                            t.HasTrigger("trCircleRecipe");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectionId"));

                    b.Property<Guid>("CollectionResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("CollectionId");

                    b.HasIndex("CollectionResourceId")
                        .IsUnique();

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("Collection", "public", t =>
                        {
                            t.HasTrigger("trCollection");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CollectionRecipe", b =>
                {
                    b.Property<int>("CollectionRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectionRecipeId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CollectionRecipeId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CollectionRecipe", "public", t =>
                        {
                            t.HasTrigger("trCollectionRecipe");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CookingLog", b =>
                {
                    b.Property<int>("CookingLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CookingLogId"));

                    b.Property<DateTime>("CookedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CookingLogResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ScaleFactor")
                        .HasColumnType("numeric");

                    b.Property<int?>("ServingsMade")
                        .HasColumnType("integer");

                    b.HasKey("CookingLogId");

                    b.HasIndex("CookedDate");

                    b.HasIndex("CookingLogResourceId")
                        .IsUnique();

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookingLog", "public", t =>
                        {
                            t.HasTrigger("trCookingLog");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CookingLogPhoto", b =>
                {
                    b.Property<int>("CookingLogPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CookingLogPhotoId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CookingLogId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CookingLogPhotoId");

                    b.HasIndex("CookingLogId");

                    b.ToTable("CookingLogPhoto", "public", t =>
                        {
                            t.HasTrigger("trCookingLogPhoto");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.DietaryProfile", b =>
                {
                    b.Property<int>("DietaryProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DietaryProfileId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietaryProfileResourceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("DietaryProfileId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("DietaryProfileResourceId")
                        .IsUnique();

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("DietaryProfile", "public", t =>
                        {
                            t.HasTrigger("trDietaryProfile");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.DietaryRestriction", b =>
                {
                    b.Property<int>("DietaryRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DietaryRestrictionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("DietaryProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RestrictionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RestrictionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DietaryRestrictionId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("DietaryProfileId", "RestrictionCode")
                        .IsUnique();

                    b.ToTable("DietaryRestriction", "public", t =>
                        {
                            t.HasTrigger("trDietaryRestriction");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipmentId"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCommon")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EquipmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("Equipment", "public", t =>
                        {
                            t.HasTrigger("trEquipment");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.ImportJob", b =>
                {
                    b.Property<int>("ImportJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImportJobId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImportJobResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsJson")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ImportJobId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("ImportJobResourceId")
                        .IsUnique();

                    b.HasIndex("LastModifiedSubjectId");

                    b.ToTable("ImportJob", "public", t =>
                        {
                            t.HasTrigger("trImportJob");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.IngredientNutrition", b =>
                {
                    b.Property<int>("IngredientNutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientNutritionId"));

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("CarbsGrams")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FatGrams")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("FdcId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FiberGrams")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GramsUsed")
                        .HasColumnType("numeric(10,3)");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MatchConfidence")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("MatchedFoodName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ProteinGrams")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("RecipeIngredientId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SodiumMg")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SugarGrams")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IngredientNutritionId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeIngredientId");

                    b.ToTable("IngredientNutrition", "public", t =>
                        {
                            t.HasTrigger("trIngredientNutrition");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.MealPlan", b =>
                {
                    b.Property<int>("MealPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealPlanId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealPlanResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MealPlanId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("MealPlanResourceId")
                        .IsUnique();

                    b.ToTable("MealPlan", "public", t =>
                        {
                            t.HasTrigger("trMealPlan");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.MealPlanEntry", b =>
                {
                    b.Property<int>("MealPlanEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealPlanEntryId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLeftover")
                        .HasColumnType("boolean");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("MealSlot")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("MealPlanEntryId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlanEntry", "public", t =>
                        {
                            t.HasTrigger("trMealPlanEntry");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ForkedFromRecipeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("MixIntent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MixedFromRecipeAId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixedFromRecipeBId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Yield")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("ForkedFromRecipeId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("MixedFromRecipeAId");

                    b.HasIndex("MixedFromRecipeBId");

                    b.HasIndex("RecipeResourceId")
                        .IsUnique();

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.ToTable("Recipe", "public", t =>
                        {
                            t.HasTrigger("trRecipe");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeEquipment", b =>
                {
                    b.Property<int>("RecipeEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeEquipmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeEquipmentId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("RecipeEquipment", "public", t =>
                        {
                            t.HasTrigger("trRecipeEquipment");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeIngredientId"));

                    b.Property<int?>("CanonicalUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Preparation")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("CanonicalUnitId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient", "public", t =>
                        {
                            t.HasTrigger("trRecipeIngredient");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeInstruction", b =>
                {
                    b.Property<int>("RecipeInstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeInstructionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.HasKey("RecipeInstructionId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeInstruction", "public", t =>
                        {
                            t.HasTrigger("trRecipeInstruction");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeLink", b =>
                {
                    b.Property<int>("RecipeLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeLinkId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IncludeInTotalTime")
                        .HasColumnType("boolean");

                    b.Property<int?>("IngredientIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("LinkedRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PortionUsed")
                        .HasColumnType("decimal(10,4)");

                    b.Property<Guid>("RecipeLinkResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeLinkId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("LinkedRecipeId");

                    b.HasIndex("ParentRecipeId");

                    b.HasIndex("RecipeLinkResourceId")
                        .IsUnique();

                    b.ToTable("RecipeLink", "public", t =>
                        {
                            t.HasTrigger("trRecipeLink");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeNutrition", b =>
                {
                    b.Property<int>("RecipeNutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeNutritionId"));

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CaloriesPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("CarbsPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CoveragePercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FatPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("FiberPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("IngredientsMatched")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientsTotal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProteinPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SodiumPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SugarPerServing")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("RecipeNutritionId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeNutrition", "public", t =>
                        {
                            t.HasTrigger("trRecipeNutrition");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<int>("RecipeTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeTagId"));

                    b.Property<Guid>("AssignedBySubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Detail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAiAssigned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NormalizedEntityType")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeTagId");

                    b.HasIndex("TagId");

                    b.HasIndex("RecipeId", "TagId")
                        .IsUnique();

                    b.ToTable("RecipeTag", "public", t =>
                        {
                            t.HasTrigger("trRecipeTag");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemTag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TagResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("TagResourceId")
                        .IsUnique();

                    b.HasIndex("Name", "Category")
                        .IsUnique();

                    b.ToTable("Tag", "public", t =>
                        {
                            t.HasTrigger("trTag");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MetricEquivalentG")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("MetricEquivalentMl")
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PluralName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnitResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("UnitId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UnitResourceId")
                        .IsUnique();

                    b.ToTable("Unit", "public", t =>
                        {
                            t.HasTrigger("trUnit");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.UnitAlias", b =>
                {
                    b.Property<int>("UnitAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitAliasId"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("UnitAliasId");

                    b.HasIndex("Alias");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitAlias", "public", t =>
                        {
                            t.HasTrigger("trUnitAlias");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.UserEquipment", b =>
                {
                    b.Property<int>("UserEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserEquipmentId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was created");

                    b.Property<Guid>("CreatedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time entity was last modified");

                    b.Property<Guid>("LastModifiedSubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("UserEquipmentId");

                    b.HasIndex("CreatedSubjectId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LastModifiedSubjectId");

                    b.HasIndex("SubjectId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("UserEquipment", "public", t =>
                        {
                            t.HasTrigger("trUserEquipment");
                        });
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.AvoidedIngredient", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.DietaryProfile", "DietaryProfile")
                        .WithMany("AvoidedIngredients")
                        .HasForeignKey("DietaryProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("DietaryProfile");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Circle", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleInvite", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Circle", "Circle")
                        .WithMany("Invites")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleMember", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Circle", "Circle")
                        .WithMany("Members")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CircleRecipe", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Circle", "Circle")
                        .WithMany("SharedRecipes")
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Collection", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CollectionRecipe", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Collection", "Collection")
                        .WithMany("CollectionRecipes")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CookingLog", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CookingLogPhoto", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.CookingLog", "CookingLog")
                        .WithMany("Photos")
                        .HasForeignKey("CookingLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CookingLog");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.DietaryProfile", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.DietaryRestriction", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.DietaryProfile", "DietaryProfile")
                        .WithMany("Restrictions")
                        .HasForeignKey("DietaryProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("DietaryProfile");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.IngredientNutrition", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.RecipeIngredient", "RecipeIngredient")
                        .WithMany()
                        .HasForeignKey("RecipeIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("RecipeIngredient");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Entries")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "ForkedFromRecipe")
                        .WithMany("Forks")
                        .HasForeignKey("ForkedFromRecipeId");

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "MixedFromRecipeA")
                        .WithMany()
                        .HasForeignKey("MixedFromRecipeAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "MixedFromRecipeB")
                        .WithMany()
                        .HasForeignKey("MixedFromRecipeBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedSubject");

                    b.Navigation("ForkedFromRecipe");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("MixedFromRecipeA");

                    b.Navigation("MixedFromRecipeB");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeEquipment", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeEquipment")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("Equipment");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Unit", "CanonicalUnit")
                        .WithMany()
                        .HasForeignKey("CanonicalUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanonicalUnit");

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeInstruction", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", null)
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeLink", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "LinkedRecipe")
                        .WithMany("UsedInRecipes")
                        .HasForeignKey("LinkedRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "ParentRecipe")
                        .WithMany("LinkedRecipes")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("LinkedRecipe");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeNutrition", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.RecipeTag", b =>
                {
                    b.HasOne("RecipeVault.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Unit", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.UnitAlias", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Unit", "Unit")
                        .WithMany("Aliases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("LastModifiedSubject");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.UserEquipment", b =>
                {
                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "CreatedSubject")
                        .WithMany()
                        .HasForeignKey("CreatedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecipeVault.Domain.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cortside.AspNetCore.Auditable.Entities.Subject", "LastModifiedSubject")
                        .WithMany()
                        .HasForeignKey("LastModifiedSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedSubject");

                    b.Navigation("Equipment");

                    b.Navigation("LastModifiedSubject");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Circle", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("SharedRecipes");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Collection", b =>
                {
                    b.Navigation("CollectionRecipes");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.CookingLog", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.DietaryProfile", b =>
                {
                    b.Navigation("AvoidedIngredients");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Forks");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("LinkedRecipes");

                    b.Navigation("RecipeEquipment");

                    b.Navigation("RecipeTags");

                    b.Navigation("UsedInRecipes");
                });

            modelBuilder.Entity("RecipeVault.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
