using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RecipeVault.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddUnitNormalization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Unit",
                schema: "public",
                columns: table => new
                {
                    UnitId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UnitResourceId = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    Abbreviation = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    PluralName = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    Type = table.Column<int>(type: "integer", nullable: false),
                    MetricEquivalentMl = table.Column<decimal>(type: "numeric(10,4)", nullable: true),
                    MetricEquivalentG = table.Column<decimal>(type: "numeric(10,4)", nullable: true),
                    SortOrder = table.Column<int>(type: "integer", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, comment: "Date and time entity was created"),
                    CreatedSubjectId = table.Column<Guid>(type: "uuid", nullable: false),
                    LastModifiedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, comment: "Date and time entity was last modified"),
                    LastModifiedSubjectId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Unit", x => x.UnitId);
                    table.ForeignKey(
                        name: "FK_Unit_Subject_CreatedSubjectId",
                        column: x => x.CreatedSubjectId,
                        principalSchema: "public",
                        principalTable: "Subject",
                        principalColumn: "SubjectId");
                    table.ForeignKey(
                        name: "FK_Unit_Subject_LastModifiedSubjectId",
                        column: x => x.LastModifiedSubjectId,
                        principalSchema: "public",
                        principalTable: "Subject",
                        principalColumn: "SubjectId");
                });

            migrationBuilder.CreateTable(
                name: "UnitAlias",
                schema: "public",
                columns: table => new
                {
                    UnitAliasId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    UnitId = table.Column<int>(type: "integer", nullable: false),
                    Alias = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, comment: "Date and time entity was created"),
                    CreatedSubjectId = table.Column<Guid>(type: "uuid", nullable: false),
                    LastModifiedDate = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, comment: "Date and time entity was last modified"),
                    LastModifiedSubjectId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UnitAlias", x => x.UnitAliasId);
                    table.ForeignKey(
                        name: "FK_UnitAlias_Subject_CreatedSubjectId",
                        column: x => x.CreatedSubjectId,
                        principalSchema: "public",
                        principalTable: "Subject",
                        principalColumn: "SubjectId");
                    table.ForeignKey(
                        name: "FK_UnitAlias_Subject_LastModifiedSubjectId",
                        column: x => x.LastModifiedSubjectId,
                        principalSchema: "public",
                        principalTable: "Subject",
                        principalColumn: "SubjectId");
                    table.ForeignKey(
                        name: "FK_UnitAlias_Unit_UnitId",
                        column: x => x.UnitId,
                        principalSchema: "public",
                        principalTable: "Unit",
                        principalColumn: "UnitId");
                });

            migrationBuilder.CreateIndex(
                name: "IX_RecipeIngredient_CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient",
                column: "CanonicalUnitId");

            migrationBuilder.CreateIndex(
                name: "IX_Unit_CreatedSubjectId",
                schema: "public",
                table: "Unit",
                column: "CreatedSubjectId");

            migrationBuilder.CreateIndex(
                name: "IX_Unit_LastModifiedSubjectId",
                schema: "public",
                table: "Unit",
                column: "LastModifiedSubjectId");

            migrationBuilder.CreateIndex(
                name: "IX_Unit_Name",
                schema: "public",
                table: "Unit",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Unit_UnitResourceId",
                schema: "public",
                table: "Unit",
                column: "UnitResourceId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_UnitAlias_Alias",
                schema: "public",
                table: "UnitAlias",
                column: "Alias");

            migrationBuilder.CreateIndex(
                name: "IX_UnitAlias_CreatedSubjectId",
                schema: "public",
                table: "UnitAlias",
                column: "CreatedSubjectId");

            migrationBuilder.CreateIndex(
                name: "IX_UnitAlias_LastModifiedSubjectId",
                schema: "public",
                table: "UnitAlias",
                column: "LastModifiedSubjectId");

            migrationBuilder.CreateIndex(
                name: "IX_UnitAlias_UnitId",
                schema: "public",
                table: "UnitAlias",
                column: "UnitId");

            migrationBuilder.AddForeignKey(
                name: "FK_RecipeIngredient_Unit_CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient",
                column: "CanonicalUnitId",
                principalSchema: "public",
                principalTable: "Unit",
                principalColumn: "UnitId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RecipeIngredient_Unit_CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient");

            migrationBuilder.DropTable(
                name: "UnitAlias",
                schema: "public");

            migrationBuilder.DropTable(
                name: "Unit",
                schema: "public");

            migrationBuilder.DropIndex(
                name: "IX_RecipeIngredient_CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient");

            migrationBuilder.DropColumn(
                name: "CanonicalUnitId",
                schema: "public",
                table: "RecipeIngredient");
        }
    }
}
