using System.Linq;
using RecipeVault.Domain.Entities;
using RecipeVault.DomainService;
using RecipeVault.Dto.Output;

namespace RecipeVault.Facade.Mappers {
    public class UnitMapper {
        public UnitDto MapToDto(Unit unit) {
            if (unit == null) {
                return null;
            }

            return new UnitDto {
                UnitId = unit.UnitId,
                UnitResourceId = unit.UnitResourceId,
                Name = unit.Name,
                Abbreviation = unit.Abbreviation,
                PluralName = unit.PluralName,
                Type = unit.Type.ToString(),
                MetricEquivalentMl = unit.MetricEquivalentMl,
                MetricEquivalentG = unit.MetricEquivalentG,
                SortOrder = unit.SortOrder,
                IsActive = unit.IsActive,
                Aliases = unit.Aliases?.Select(a => new UnitAliasDto {
                    UnitAliasId = a.UnitAliasId,
                    Alias = a.Alias,
                    IsAutoGenerated = a.IsAutoGenerated
                }).ToList()
            };
        }

        public UnitMatchResultDto MapToDto(UnitMatchResult result) {
            if (result == null) {
                return null;
            }

            return new UnitMatchResultDto {
                IsMatch = result.IsMatch,
                Unit = result.MatchedUnit != null ? MapToDto(result.MatchedUnit) : null,
                Confidence = result.Confidence,
                OriginalInput = result.OriginalInput
            };
        }
    }
}
