using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Cortside.AspNetCore.Auditable.Entities;
using Microsoft.EntityFrameworkCore;

namespace RecipeVault.Domain.Entities {
    [Index(nameof(Alias))]
    [Table("UnitAlias")]
    public class UnitAlias : AuditableEntity {
        protected UnitAlias() {
        }

        public UnitAlias(Unit unit, string alias, bool isAutoGenerated = false) {
            Unit = unit;
            UnitId = unit.UnitId;
            Alias = alias;
            IsAutoGenerated = isAutoGenerated;
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UnitAliasId { get; private set; }

        public int UnitId { get; private set; }

        [ForeignKey(nameof(UnitId))]
        public virtual Unit Unit { get; private set; }

        [Required]
        [StringLength(50)]
        public string Alias { get; private set; }

        public bool IsAutoGenerated { get; private set; }
    }
}
