using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Cortside.AspNetCore.Auditable.Entities;
using Microsoft.EntityFrameworkCore;
using RecipeVault.Domain.Enums;
using UUIDNext;

namespace RecipeVault.Domain.Entities {
    [Index(nameof(UnitResourceId), IsUnique = true)]
    [Index(nameof(Name), IsUnique = true)]
    [Table("Unit")]
    public class Unit : AuditableEntity {
        protected Unit() {
        }

        public Unit(string name, string abbreviation, string pluralName, UnitType type, decimal? metricEquivalentMl, decimal? metricEquivalentG, int sortOrder) {
            UnitResourceId = Uuid.NewDatabaseFriendly(Database.SqlServer);
            aliases = new List<UnitAlias>();
            IsActive = true;
            Update(name, abbreviation, pluralName, type, metricEquivalentMl, metricEquivalentG, sortOrder);
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UnitId { get; private set; }

        public Guid UnitResourceId { get; private set; }

        [Required]
        [StringLength(50)]
        public string Name { get; private set; }

        [Required]
        [StringLength(10)]
        public string Abbreviation { get; private set; }

        [StringLength(50)]
        public string PluralName { get; private set; }

        public UnitType Type { get; private set; }

        [Column(TypeName = "numeric(10,4)")]
        public decimal? MetricEquivalentMl { get; private set; }

        [Column(TypeName = "numeric(10,4)")]
        public decimal? MetricEquivalentG { get; private set; }

        public int SortOrder { get; private set; }

        public bool IsActive { get; private set; }

        private readonly List<UnitAlias> aliases = new();
        public virtual IReadOnlyList<UnitAlias> Aliases => aliases;

        public void Update(string name, string abbreviation, string pluralName, UnitType type, decimal? metricEquivalentMl, decimal? metricEquivalentG, int sortOrder) {
            Name = name;
            Abbreviation = abbreviation;
            PluralName = pluralName;
            Type = type;
            MetricEquivalentMl = metricEquivalentMl;
            MetricEquivalentG = metricEquivalentG;
            SortOrder = sortOrder;
        }

        public void AddAlias(string alias, bool isAutoGenerated = false) {
            aliases.Add(new UnitAlias(this, alias, isAutoGenerated));
        }

        public void SetActive(bool isActive) {
            IsActive = isActive;
        }
    }
}
