using System;
using System.Collections.Generic;
using Cortside.AspNetCore.Common.Dtos;

namespace RecipeVault.Dto.Output {
    public class UnitDto : AuditableEntityDto {
        public int UnitId { get; set; }
        public Guid UnitResourceId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string PluralName { get; set; }
        public string Type { get; set; }
        public decimal? MetricEquivalentMl { get; set; }
        public decimal? MetricEquivalentG { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public List<UnitAliasDto> Aliases { get; set; }
    }

    public class UnitAliasDto {
        public int UnitAliasId { get; set; }
        public string Alias { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
